name: Copy File

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  schedule:
    - cron: '0 0 1,15 * *'  # 在每个月的1号和15号的零点触发

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pcr-wiki repository
      uses: actions/checkout@v4
      

    - name: Copy _pcr_data.py from LandosolRoster
      run: |
        curl -o pcr-wiki/spider/_pcr_data.py -L https://raw.githubusercontent.com/aJacke/LandosolRoster/main/_pcr_data.py
      
    - name: add commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'update _pcr_data.py'
        add: './_pcr_data.py'
          
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Copy _pcr_data.py from LandosolRoster"
        git push
